@startuml
'https://plantuml.com/class-diagram
scale 1

package DED{

    class Des{
    m_nblancer : Integer
    m_nbface : Integer
    }


    package Objets {



        class Equipement {
            + m_coordonées : Couple
            + m_nom : String
            + m_personnage : Personnages
            + recupererObjet(Personnages peronnage)
            + DesequiperObjet()
            + getCoordonées() : Couple
            + toString() : String

        }

        class Arme extends Equipement
        {

                + m_degat : Interger
                + m_portée : Interger
                + toString() : String
        }

        enum TypeArme extends Arme
        {
            CAC
            GUERRECAC
            DISTANCE
        }

        class Armure extends Equipement
        {
                + <<create>> Armure()
                + m_classe : Interger
                + toString() : String
        }

        enum TypeArmure    extends Armure
        {
            LOURDE
            LEGERE
        }

    }

    package Creatures {
            interface Entitee
            {
                + m_nom : String
                + m_coordonées : Couple
                + attaquer(Entite entite)
                + defense(Integer attaque)
                + getCoordonées() : Couple
                + setCoordonées(Couple coordonées)
            }

            class Personnages implements Entitee
            {
                +<<create>> Personnage(nom : String)
                +attaquer(Monstres monstre)
                +defense(Integer pointsAttaque) : Boolean
            }

            class Race
            {
                + <<create>> Race (race:String)
                + m_vie  : Integer
                + m_force : Integer
                + m_dexterite: Integer
                + m_vitesse : Integer
                + m_initiative : Integer
                + getStats() : Integer[]

            }

            class Humain extends Race
            {
                +<<create>> Humain(monstres : String)

            }

            class Halfelins extends Race
            {
                +<<create>> Halfelins(race : String)

            }

            class Elfes extends Race
            {
                +<<create>> Elfes(monstres : String)

            }

            class Nains extends Race
            {
                +<<create>> Nains (monstres : String)

            }

            class Classe
            {
                +<<create>> Classe(classe: String)
                +m_vie : Integer
            }

            class Clercs extends Classe
            {
                +<<create>> Clercs(classe : String)


            }

            class Guerriers extends Classe
            {
                +<<create>> Guerriers(classe : String)

            }

            class Magiciens extends Classe
            {
                +<<create>> Magiciens(classe : String)
            }

            class Roublards extends Classe
            {
                +<<create>> Roublards(classe : String)
            }

            class Monstres implements Entitee
            {

                +<<create>> Monstre(nom : String)
                +attaquer(Personnages)
                +defense(Integer pointsAttaque) : Boolean
            }

            class Espece
            {
                +m_nom : String
                +m_vie  : Integer
                +m_dexterite: Integer
                +m_force : Integer
                +m_vitesse : Integer
                +m_initiative : Integer
            }

    }


    class Donjon
    {
        + m_tabObjet : (Objet[])
        + m_tabEntitee : (Entitee[])
        + afficherDonjon(Interger nMap) :
        + genererDonjon(Entitee[], Objet[]) : String
    }

}


Donjon o--> Equipement : > coordonées
Donjon o--> Entitee: > coordonées
Personnages *--> Race
Personnages *--> Classe
Monstres *--> Espece
Des *-> Personnages
Des *-> Race
Des *-> Monstres




@enduml