@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

package ded {

    class Donjon {
        + <<create>> Donjon(nom : String)
        + m_tabObjet : Equipement[*]
        + m_tabEntitee : Entite[*]
        + afficherDonjon(nMap : Integer)
        + genererDonjon(tabEntitee : Entite[*], tabObjet : Equipement[*]) : String
    }

    class Main {
        + {static} main(args : String[*])
    }

    class Des {
        + {static} lancer(faces : Integer)
        + {static} lancerMultiple(nbDes : Integer, faces : Integer)
        + {static} lancerAvecBonus(nbDes : Integer, faces : Integer, bonus : Integer)
    }

    package objets {

        abstract class Equipement <<abstract>> {
            + <<create>> Equipement()
            + m_coordonnees : Integer[*]
            + m_nom : String
            + m_personnage : Personnage
            + recupererObjet(personnage : Personnage)
            + desequiperObjet()
            + getCoordonnees() : Integer[*]
            + toString() : String
        }

        class Arme extends Equipement {
            + <<create>> Arme()
            + m_degat : Integer
            + m_portee : Integer
            + toString() : String
        }

        enum TypeArme <<enumerate>> {
            CAC
            GUERRECAC
            DISTANCE
        }

        class Armure extends Equipement {
            + <<create>> Armure()
            + m_classe : Integer
            + toString() : String
        }

        enum TypeArmure <<enumerate>> {
            LOURDE
            LEGERE
        }
    }

    package creatures {

        interface Entite <<interface>> {
            + m_nom : String
            + m_coordonnees : Integer[*]
            + {abstract} //attaquer(entite : Entite)//
            + {abstract} //defense(attaque : Integer)//
            + {abstract} //getCoordonnees() : Integer[*]//
            + {abstract} //setCoordonnees(coordonnees : Integer[*])//
            + {abstract} //getNom() : String//
        }

        class Personnage implements Entite {
            + <<create>> Personnage(nom : String)
            + attaquer(monstre : Monstre)
            + defense(pointsAttaque : Integer) : Boolean
        }

        abstract class Race <<abstract>> {
            + <<create>> Race(race : String)
            + m_force : Integer
            + m_dexterite : Integer
            + m_vitesse : Integer
            + m_initiative : Integer
            + getStats() : Integer[*]
        }

        class Humain extends Race {
            + <<create>> Humain(race : String)
        }

        class Halfelin extends Race {
            + <<create>> Halfelin(race : String)
        }

        class Elfe extends Race {
            + <<create>> Elfe(race : String)
        }

        class Nain extends Race {
            + <<create>> Nain(race : String)
        }

        abstract class Classe <<abstract>> {
            + m_vie : Integer
        }

        class Clerc extends Classe {
            + m_vie : Integer
            + <<create>> Clerc(classe : String)
            + getVie() : Integer

        }

        class Guerrier extends Classe {
            + m_vie : Integer
            + <<create>> Guerrier(classe : String)
            + getVie() : Integer
        }

        class Magicien extends Classe {
            + m_vie : Integer
            + <<create>> Magicien(classe : String)
            + getVie() : Integer
        }

        class Roublard extends Classe {
            + m_vie : Integer
            + <<create>> Roublard(classe : String)
            + getVie() : Integer
        }

        class Monstre implements Entite {
            + <<create>> Monstre(nom : String)
            + attaquer(personnage : Personnage)
            + defense(pointsAttaque : Integer) : Boolean
        }

        class Espece {
            + <<create>> Espece(nom : String)
            + m_nom : String
            + m_vie : Integer
            + m_dexterite : Integer
            + m_force : Integer
            + m_vitesse : Integer
            + m_initiative : Integer
        }
    }


    Personnage *--> Race
    Personnage *--> Classe
    Monstre *-> Espece

    Personnage "1" o-> "0..*" Equipement : possède >

    Donjon "1" o-> "0..*" Equipement : contient >
    Donjon "1" o-> "0..*" Entite : contient >

    Des .-> Personnage : <<use>>
    Des .-> Race : <<use>>
    Des .-> Monstre : <<use>>
    TypeArme .> Arme : <<use>>
    TypeArmure .> Armure : <<use>>

}

@enduml

